"""
app/evolution_engine/skill_creator.py

Gives Agent 6 a controlled API to write new .py skill files inside app/tools/.
Validates that files are only created in allowed directories.
"""

import json
from pathlib import Path
from datetime import datetime, timezone


ALLOWED_CATEGORIES = {"document_skills", "research_skills", "superpowers"}
TOOLS_ROOT = Path("app/tools")


def create_skill(filename: str, code: str, category: str) -> Path:
    """
    Write a new Python skill file to app/tools/<category>/<filename>.

    Args:
        filename: e.g. 'brand_fix_abc12345.py'
        code:     Python source code string
        category: one of 'document_skills', 'research_skills', 'superpowers'

    Returns:
        Path to the created file.

    Raises:
        ValueError: if category is not in ALLOWED_CATEGORIES
    """
    if category not in ALLOWED_CATEGORIES:
        raise ValueError(
            f"Skill category '{category}' not allowed. Must be one of: {ALLOWED_CATEGORIES}"
        )
    if not filename.endswith(".py"):
        filename += ".py"

    skill_dir = TOOLS_ROOT / category
    skill_dir.mkdir(parents=True, exist_ok=True)

    skill_path = skill_dir / filename

    header = f"""# Auto-generated by AgentPress Meta-Engineer
# Created: {datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")}
# Category: {category}
# ─────────────────────────────────────────────────────────────────────────────

"""
    full_code = header + code
    skill_path.write_text(full_code, encoding="utf-8")

    # Log the creation in a skills registry JSON
    registry_path = TOOLS_ROOT / "skills_registry.json"
    registry = []
    if registry_path.exists():
        try:
            registry = json.loads(registry_path.read_text())
        except Exception:
            registry = []

    registry.append({
        "filename": filename,
        "category": category,
        "path": str(skill_path),
        "created_at": datetime.now(timezone.utc).isoformat(),
    })
    registry_path.write_text(json.dumps(registry, indent=2))

    return skill_path
