# Auto-generated by AgentPress Meta-Engineer
# Created: 2026-04-08 15:11 UTC
# Category: document_skills
# ─────────────────────────────────────────────────────────────────────────────

import collections
import collections.abc
from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.enum.text import PP_ALIGN
import re

def apply_brand_fix(draft_text: str, output_path: str, research_brief: str = "") -> bool:
    """
    Fixes Data Integrity and Hallucination failures in the PPTX pipeline.
    
    This function implements a Strict Grounding Enforcement layer by:
    1. Validating draft_text against the research_brief to identify potential hallucinations 
       (specifically looking for numeric metrics not present in source).
    2. Enforcing a schema-strict slide generation to prevent truncation.
    3. Ensuring footer injection is synchronized with the final XML write.
    
    Args:
        draft_text (str): The LLM generated content (expected format: Slide X: Title \n Content).
        output_path (str): Path to save the validated .pptx file.
        research_brief (str): The ground truth source to validate against.
        
    Returns:
        bool: True if file created successfully, False if critical hallucination detected.
    """
    # Hallucination Check: Identify numbers/percentages in draft not in brief
    if research_brief:
        draft_metrics = re.findall(r'\d+%', draft_text)
        for metric in draft_metrics:
            if metric not in research_brief:
                # Logically flag or strip hallucinations; here we prevent the build to trigger retry
                return False

    prs = Presentation()
    
    # Define Brand Constants
    FOOTER_TEXT = "AgentPress Confidential - Internal Roadmap"
    
    # Parse slides using a strict regex to prevent truncation/loop errors
    slides_data = re.split(r'Slide \d+:', draft_text)[1:]
    
    if not slides_data:
        # Fallback if LLM failed the formatting
        slides_data = [draft_text]

    for slide_content in slides_data:
        slide_layout = prs.slide_layouts[1] # Bullet point layout
        slide = prs.slides.add_slide(slide_layout)
        
        lines = [line.strip() for line in slide_content.strip().split('\n') if line.strip()]
        
        if not lines:
            continue
            
        # Title Assignment
        title_shape = slide.shapes.title
        title_shape.text = lines[0]
        
        # Body Content Assignment
        body_shape = slide.placeholders[1]
        tf = body_shape.text_frame
        tf.word_wrap = True
        
        for i, bullet in enumerate(lines[1:]):
            if i == 0:
                p = tf.paragraphs[0]
            else:
                p = tf.add_paragraph()
            p.text = bullet
            p.level = 0
            
        # Synchronized Footer Injection (Prevents Stage 1 vs Stage 2 discrepancy)
        left = Inches(0.5)
        top = Inches(7.1)
        width = Inches(9)
        height = Inches(0.3)
        footer_box = slide.shapes.add_textbox(left, top, width, height)
        footer_p = footer_box.text_frame.paragraphs[0]
        footer_p.text = FOOTER_TEXT
        footer_p.font.size = Pt(10)
        footer_p.alignment = PP_ALIGN.LEFT

    try:
        prs.save(output_path)
        return True
    except Exception:
        return False