# Auto-generated by AgentPress Meta-Engineer
# Created: 2026-04-10 07:55 UTC
# Category: document_skills
# ─────────────────────────────────────────────────────────────────────────────

import re
import logging

def apply_brand_fix(draft_text: str, output_path: str) -> bool:
    """
    Validates draft content for factual integrity by identifying and flagging 
    placeholders or hallucinated data points before final document generation.
    
    This function addresses Stage 1 Factual Integrity Violations where the LLM 
    fills missing data with 'optimistic corporate filler'. It scans for 
    common placeholder patterns and 'Null' indicators, ensuring that 
    unverified data does not reach the PPTX Builder.

    Args:
        draft_text (str): The raw text generated for the QBR or report.
        output_path (str): Path to save the validated/flagged report.

    Returns:
        bool: True if the content is clean and valid; False if data gaps were found.
    """
    # Patterns indicating missing data or placeholders that trigger hallucinations
    missing_data_patterns = [
        r"\[DATA NOT RETRIEVED\]",
        r"REQUIRES MANUAL SYNC",
        r"REQUIRES SYNC WITH RAGFLOW",
        r"\[INSERT .*?\]",
        r"TBD",
        r"PENDING DATA",
        r"0\.0% variance" # Often a sign of a default value for missing math
    ]
    
    found_gaps = []
    for pattern in missing_data_patterns:
        if re.search(pattern, draft_text, re.IGNORECASE):
            found_gaps.append(pattern)

    if found_gaps:
        error_msg = f"CRITICAL: Factual Integrity Breach. Missing data detected: {found_gaps}"
        logging.error(error_msg)
        
        # Prepend a warning to the draft so the PPTX builder or human reviewer sees the failure
        flagged_content = f"### DATA VALIDATION FAILURE: {', '.join(found_gaps)} ###\n\n{draft_text}"
        
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(flagged_content)
        
        return False

    # If clean, write the draft to the output path for the next stage
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(draft_text)
        
    return True