# Auto-generated by AgentPress Meta-Engineer
# Created: 2026-04-08 13:57 UTC
# Category: document_skills
# ─────────────────────────────────────────────────────────────────────────────

import os
from pathlib import Path
from docx import Document
from docx.shared import Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH

def apply_brand_fix(draft_text: str, output_path: str) -> bool:
    """
    Fixes AgentPress brand compliance failures in document generation.
    
    1. Corrects the 'Normal' style font color from NAVY to OFF_WHITE (#EAEAEA).
    2. Completes the truncated footer logic to include the mandatory 
       'CONFIDENTIAL - AgentPress Internal' string.
    
    Args:
        draft_text (str): The raw content to be injected into the document.
        output_path (str): The file path where the fixed .docx will be saved.
        
    Returns:
        bool: True if the document was successfully created and saved.
    """
    try:
        # Ensure output directory exists
        out_file = Path(output_path)
        out_file.parent.mkdir(parents=True, exist_ok=True)

        doc = Document()

        # Brand Colors
        NAVY = RGBColor(0x1A, 0x1A, 0x2E)
        CRIMSON = RGBColor(0xE9, 0x45, 0x60)
        OFF_WHITE = RGBColor(0xEA, 0xEA, 0xEA)

        # FIX 1: Correct Text Color (Brand Goal Violation)
        style = doc.styles['Normal']
        style.font.name = 'Calibri'
        style.font.size = Pt(11)
        style.font.color.rgb = OFF_WHITE  # Corrected from NAVY

        # Header Implementation
        header = doc.sections[0].header
        htable = header.add_table(1, 1, doc.sections[0].width)
        htable.rows[0].cells[0].text = "AGENTPRESS"
        h_run = htable.rows[0].cells[0].paragraphs[0].runs[0]
        h_run.font.bold = True
        h_run.font.size = Pt(18)
        h_run.font.color.rgb = CRIMSON

        # Content Injection
        doc.add_paragraph(draft_text)

        # FIX 2: Complete Footer Logic (Incomplete Implementation)
        footer = doc.sections[0].footer
        # Ensure at least one paragraph exists in the footer
        f_para = footer.paragraphs[0] if footer.paragraphs else footer.add_paragraph()
        f_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
        
        f_run = f_para.add_run("CONFIDENTIAL - AgentPress Internal")
        f_run.font.size = Pt(9)
        f_run.font.color.rgb = NAVY  # Footers use Navy accent per guidelines

        doc.save(str(out_file))
        return True

    except Exception as e:
        print(f"Pipeline Error: {e}")
        return False